# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22a5877eceada8b7f9c5b1d057cc51ee2f769a4b10b0ddbc9ce54036eefe144a63116eecda702d780ae21e568c8f59ab5708b13088699577686884776e9d3656

test:
  secret_key_base: 49705d11dd8f3469c49572de27b25d2e77f2ab2ae75d9b16eb13d8d6b81456553cff3a863e64b7ef862362fabe0cb605c9c58947fd4adba7151f8c9076211549

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
